/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nounsbetTableProxyAdminSol from "./NounsbetTableProxyAdmin.sol";
export { NounsbetTableProxy__factory } from "./NounsbetTableProxy__factory";
