/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nounsbetTableProxyAdminSol from "./NounsbetTableProxyAdmin.sol";
export type { nounsbetTableProxyAdminSol };
export type { NounsbetTableProxy } from "./NounsbetTableProxy";
