/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NounsbetProxy__factory } from "./NounsbetProxy__factory";
export { NounsbetTable__factory } from "./NounsbetTable__factory";
